
package com.phone.dir.application.contact_registry_apis_soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactsWebService", targetNamespace = "http://contact_registry_apis_soap.webservice.registry.contact/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactsWebService {


    /**
     * 
     * @param userName
     * @return
     *     returns contact.registry.webservice.contact_registry_apis_soap.Contact
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://contact_registry_apis_soap.webservice.registry.contact/ContactsWebService/getContactsTestRequest", output = "http://contact_registry_apis_soap.webservice.registry.contact/ContactsWebService/getContactsTestResponse")
    public Contact getContactsTest(
        @WebParam(name = "userName", partName = "userName")
        String userName);

    /**
     * 
     * @param organizationName
     * @return
     *     returns contact.registry.webservice.contact_registry_apis_soap.ContactListResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://contact_registry_apis_soap.webservice.registry.contact/ContactsWebService/getContactsByOrganizationNameRequest", output = "http://contact_registry_apis_soap.webservice.registry.contact/ContactsWebService/getContactsByOrganizationNameResponse")
    public ContactListResponse getContactsByOrganizationName(
        @WebParam(name = "organizationName", partName = "organizationName")
        String organizationName);

}
